if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    include(PerfAppClangFlags)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    include(PerfAppGCCFlags)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    include(PerfAppMSVCFlags)
else()
    message(FATAL_ERROR "Unsupported compiler: ${CMAKE_CXX_COMPILER_ID}")
endif()
